### ISSUE TITLE
Kész

### ISSUE THREAD

**Issue by Fmiri08** [Teaching-projects/SOE-ProgAlap2-Beadando-Sudoku2#1]
Szia! úgy érzem kész a beadandóm, ha lesz időd és rá tudsz nézni azt előre is köszönöm!

**Comment by hegyhati** [comment]
Meglestem. Kar, hogy ennyire last minute adtad le. Kicsit pofozva az otos is kihozhato lett volna, de igy most a negyest tudom beirni.
